#
# This is free software, license use GPLv3.
#
# Copyright (c) 2020, Chuck <fanck0605@qq.com>
#

name: openwrt-master TestV3.7

on:
  push:
    branches:
      - openwrt-master
  # schedule:
   #  - cron: '00 18 * * *'
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      # 设置变量
      - name: set env
        id: admin
        run: |
          release_tag="tput files
archive_tag=OpenWrt-FYMSC-NanoPi-R2S_v3.7$(date +%y%m%d%H%M%S)"
          echo "##[set-output name=release_tag;]$release_tag"
          # 引用变量
          # ${{ steps.admin.outputs.release_tag }}

      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: openwrt-master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker image prune -a -f
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get update
          sudo -E apt-get -y install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
          wget -O- https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
      - name: Build OpenWrt
        run: |
          # 给./buildtest.sh添加权限，不然无法编译
          chmod +x ./buildtest.sh
          ./buildtest.sh
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.admin.outputs.release_tag }}
          path: OpenWRT-*.tar.gz
